- src: geerlingguy.apache
  version: 3.1.0

- src: geerlingguy.php-versions
  version: 4.0.4

- src: geerlingguy.php
  version: 4.5.1

- src: geerlingguy.composer
  version: 1.9.0

- src: geerlingguy.mysql
  version: 3.3.0

- src: geerlingguy.redis
  version: 1.6.0

- src: geerlingguy.certbot
  version: 3.0.2